### ISSUE TITLE
How to program CPLD

### ISSUE THREAD

**Issue by mamejay** [niklasekstrom/clockport_pi_interface#2]
Hello there.  Just wondering how the CPLD gets programmed.  Is it through the Pi itself?
Thanks

**Comment by niklasekstrom** [comment]
Hi @mamejay! I must have missed the notification for your message, I saw it first now.

Yes this is correct, using the pi.

In the release there is a program, https://github.com/niklasekstrom/clockport_pi_interface/releases/download/v1.1/xc3sprog, that can be used to write the configuration to the cpld.

A precompiled configuration binary, that works for this pcb layout (but not for Eriond's pcb layout) is available in the release too: https://github.com/niklasekstrom/clockport_pi_interface/releases/download/v1.1/cp_pi_if.jed

The command line to use for programming is: `sudo ./xc3sprog -c sysfsgpio_creator -v cp_pi_if.jed:w`

I don't remember if I compiled xc3sprog for 32 or 64 bit Linux. If your Raspberry Pi OS is the wrong bitness then the repo with the small change needed is here: https://github.com/niklasekstrom/xc3sprog
